# Generated by Django 5.2 on 2025-06-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        ('komissiya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komissiyamember',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.level'),
        ),
    ]
