# Generated by Django 5.2 on 2025-06-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komissiya', '0002_komissiyamember_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komissiyamember',
            name='level',
        ),
    ]
