# Generated by Django 5.2 on 2025-07-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadminuser',
            name='full_name',
        ),
    ]
