# Generated by Django 5.2 on 2025-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('item',), name='unique_score_per_application_item'),
        ),
    ]
