# Generated by Django 5.2 on 2025-07-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='hemis_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
