# Generated by Django 5.2 on 2025-07-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinfo',
            name='gpa',
            field=models.FloatField(null=True),
        ),
    ]
