# Generated by Django 5.2 on 2025-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='toifa',
            field=models.BooleanField(default=False),
        ),
    ]
