# Generated by Django 5.1.2 on 2025-06-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'direction')},
        ),
        migrations.RemoveField(
            model_name='customadminuser',
            name='course',
        ),
        migrations.RemoveField(
            model_name='customadminuser',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='customadminuser',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='customadminuser',
            name='section',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='file',
        ),
        migrations.AddField(
            model_name='customadminuser',
            name='courses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customadminuser',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='admins', to='apps.direction'),
        ),
        migrations.AddField(
            model_name='customadminuser',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='admins', to='apps.faculty'),
        ),
        migrations.AddField(
            model_name='customadminuser',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='admins', to='apps.section'),
        ),
        migrations.AddField(
            model_name='historicalscore',
            name='section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.section'),
        ),
        migrations.AddField(
            model_name='score',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='apps.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direction',
            name='max_score',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='score',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='apps.application'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('application', 'section')},
        ),
        migrations.CreateModel(
            name='ApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applications/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='apps.application')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_files', to='apps.section')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='application',
            name='file',
        ),
    ]
