# Generated by Django 5.2 on 2025-07-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_contractinfo_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='customadminuser',
            name='university1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.university'),
        ),
        migrations.AddField(
            model_name='student',
            name='university1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.university', unique=True),
        ),
    ]
