# Generated by Django 5.2 on 2025-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_faculty_hemis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='hemis_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('hemis_id', 'name')},
        ),
    ]
