# Generated by Django 5.1.2 on 2025-06-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kurs / Bosqich',
                'verbose_name_plural': 'Kurs / Bosqichlar',
            },
        ),
        migrations.RemoveField(
            model_name='customadminuser',
            name='courses',
        ),
        migrations.AddField(
            model_name='customadminuser',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='admins', to='apps.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.level'),
        ),
    ]
