# Generated by Django 5.2 on 2025-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_score_unique_score_per_application_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
