# Generated by Django 5.2 on 2025-07-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_student_toifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='access_type',
            field=models.CharField(choices=[('universal', 'Hamma talabalar uchun'), ('min_gpa', 'GPA talab'), ('special_list', 'Faqat maxsus ro‘yxatdagi talabalar'), ('maxsus', 'Ijtimoiy ximoya reestridagi talabalar')], default='universal', max_length=20),
        ),
    ]
