# Generated by Django 5.2 on 2025-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_applicationtype_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='direction_type',
            field=models.CharField(choices=[('file', 'File'), ('test', 'Test'), ('gpa', 'GPA'), ('toifa', 'Reestr')], default='file', max_length=10),
        ),
        migrations.AlterField(
            model_name='direction',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('test', 'Test'), ('gpa', 'GPA'), ('toifa', 'Reestr')], default='file', max_length=10),
        ),
    ]
