# Generated by Django 5.2 on 2025-07-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_customadminuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadminuser',
            name='full_name',
        ),
    ]
