# Generated by Django 5.2 on 2025-07-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='direction',
        ),
    ]
