# Generated by Django 5.2 on 2025-07-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_university_customadminuser_university1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.university'),
        ),
    ]
