# Generated by Django 5.2 on 2025-07-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_customadminuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadminuser',
            name='full_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
