# Generated by Django 5.2 on 2025-07-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_student_university1'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
