# Generated by Django 5.2 on 2025-07-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_application_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='apps.direction'),
        ),
    ]
