# Generated by Django 5.2 on 2025-07-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_testsession_current_question_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='hemis_id',
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(default='Unknown', max_length=255, null=True),
        ),
    ]
