# Generated by Django 5.2 on 2025-07-06 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_application_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='apps.section'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationitem',
            unique_together={('application', 'direction')},
        ),
    ]
