# Generated by Django 5.2 on 2025-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_customadminuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationitem',
            name='gpa_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
