# Generated by Django 5.2 on 2025-07-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_faculty_hemis_id_university_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
    ]
