# Generated by Django 5.2 on 2025-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_university_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
