# Generated by Django 5.2 on 2025-07-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_applicationfile_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfile',
            name='item',
        ),
        migrations.AddField(
            model_name='applicationfile',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='apps.application'),
            preserve_default=False,
        ),
    ]
