# Generated by Django 5.2 on 2025-07-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_applicationfile_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfile',
            name='application',
        ),
        migrations.AddField(
            model_name='applicationfile',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='apps.applicationitem'),
            preserve_default=False,
        ),
    ]
