# Generated by Django 5.2 on 2025-07-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_applicationfile_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadminuser',
            name='can_score',
            field=models.BooleanField(default=True, help_text='Agar true bo‘lsa, admin baho qo‘yishi mumkin.'),
        ),
    ]
