# Generated by Django 5.2 on 2025-07-06 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_customadminuser_can_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfile',
            name='application_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_files', to='apps.applicationitem'),
            preserve_default=False,
        ),
    ]
