# Generated by Django 5.2 on 2025-07-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_applicationfile_application_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfile',
            name='application_item',
        ),
    ]
