# Generated by Django 5.2 on 2025-07-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_question_test_option_question_test_testsession_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsession',
            old_name='start_time',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='completed',
        ),
        migrations.AddField(
            model_name='testsession',
            name='correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='questions',
            field=models.ManyToManyField(to='apps.question'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
