# Generated by Django 5.2 on 2025-07-07 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_rename_start_time_testsession_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 7, 8, 13, 12, 892452, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='levels',
            field=models.ManyToManyField(related_name='tests', to='apps.level'),
        ),
    ]
