# Generated by Django 5.2 on 2025-07-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='questions',
            field=models.ManyToManyField(blank=True, to='apps.question'),
        ),
    ]
