# Generated by Django 5.2 on 2025-07-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_alter_testsession_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testsession',
            unique_together={('student', 'test')},
        ),
    ]
