# Generated by Django 5.2 on 2025-07-08 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_testsession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='direction_type',
            field=models.CharField(choices=[('file', 'File'), ('test', 'Test'), ('gpa', 'GPA')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='direction',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.test'),
        ),
    ]
