# Generated by Django 5.2 on 2025-07-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_direction_direction_type_direction_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='apps.direction'),
            preserve_default=False,
        ),
    ]
