# Generated by Django 5.2 on 2025-07-08 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_application_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='direction',
        ),
    ]
