# Generated by Django 5.2 on 2025-07-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_remove_application_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('test', 'Test'), ('gpa', 'GPA')], default='file', max_length=10),
        ),
    ]
