# Generated by Django 5.2 on 2025-07-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_applicationitem_gpa_applicationitem_test_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdobAxloqStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabab', models.CharField(max_length=500)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odob_axloq_talaba', to='apps.student')),
            ],
        ),
    ]
