# Generated by Django 5.2 on 2025-07-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_odobaxloqstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odobaxloqstudent',
            name='talaba',
        ),
        migrations.AddField(
            model_name='odobaxloqstudent',
            name='hemis_id',
            field=models.CharField(default=14, max_length=20),
            preserve_default=False,
        ),
    ]
